SELECT A.MATRICULA, A.NOME, A.IDADE, A.ESTADO, B.NOME AS NOMECAMPOS, B.ESTADO AS ESTADOCAMPOS
FROM		ALUNOS AS A WITH(NOLOCK)
INNER JOIN	CAMPUS AS B WITH(NOLOCK) ON A.ESTADO = B.ESTADO
ORDER BY A.MATRICULA